app:
  name: intask-backend
  version: 0.0.1
  env: dev

server:
  http:
    addr: localhost:8001
    tls:
      enable: false
      server_cert_path: ./certs/server.crt
      server_key_path: ./certs/server.key
  conns:
    read_timeout: 2s
    write_timeout: 2s
    idle_timeout: 30s

// TODO: вынести пг в .env godotenv
persistence:
  migrations_path: ./migrations
  postgres:
    host: localhost
    port: 5432
    sslmode: disable
    auth:
      user: chishkin
      password: 1111
      db: intask
    conns:
      max_opens: 5
      max_idles: 15
      max_lifetime: 15m
      max_idle_time: 30m

jwt:
  ttl: 168h
  private_key_path: ./keys/jwtRS256.key
  public_key_path: ./keys/jwtRS256.key.pub

telegram:
  bot_token: "token"
  timeout: 30s